### ISSUE TITLE
Issue for changing the status code

### ISSUE THREAD

**Issue by amalrajgit** [amalrajs1990/Whatzapp#5]
Dear amal,

  I have found some isssues on status code. pls find the attached copy
[facebook.txt](https://github.com/amalrajs1990/Whatzapp/files/6270457/facebook.txt)

**Comment by amalrajs1990** [comment]
Ok good. i will let you know once fixing the issue.. keep your support

**Comment by amalrajs1990** [comment]
Dear amal,

fixed bug as per your concern
